language: node_js

matrix:
    fast_finish: true

    include:
        - node_js: "0.10"
        - node_js: "0.12"
        - node_js: "4.0"
        - node_js: "4.1"
        - node_js: "4.2"

sudo: false
